// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Trackable.Models;

namespace Trackable.Web.Dtos
{
    public class AssetDto
    {
        /// <summary>
        /// Asset id, Autogenerated or Specified
        /// </summary>
        public string Id { get; set; }

        /// <summary>
        /// The asset name
        /// </summary>
        [Required]
        public string Name { get; set; }

        /// <summary>
        /// The id of the tracking device associated with this asset.
        /// Can be changed to relink to another device.
        /// </summary>
        public string TrackingDeviceId { get; set; }

        /// <summary>
        /// The tracking device associated with this asset
        /// </summary>
        public TrackingDeviceDto TrackingDevice { get; set; }

        /// <summary>
        /// The asset type
        /// </summary>
        [Required]
        [JsonConverter(typeof(StringEnumConverter))]
        public AssetType AssetType { get; set; }

        /// <summary>
        /// Extended asset properties required if the asset is a truck
        /// </summary>
        public AssetPropertiesDto AssetProperties { get; set; }

        /// <summary>
        /// Tags
        /// </summary>
        public IEnumerable<string> Tags { get; set; }
    }
}
