// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

using System.ComponentModel.DataAnnotations;

namespace Trackable.Web.Dtos
{
    public class UserDto
    {
        /// <summary>
        /// User id, Autogenerated or Specified
        /// </summary>
        public string Id { get; set; }

        /// <summary>
        /// User Email
        /// </summary>
        [Required]
        public string Email { get; set; }

        /// <summary>
        /// User Name
        /// </summary>
        [Required]
        public string Name { get; set; }

        /// <summary>
        /// User Role
        /// </summary>
        [Required]
        public RoleDto Role { get; set; }
    }
}
